<?php
$title = $this->translate( 'Add a Comment' );
$this->headTitle( $title );?>
<h1><?php echo $this->escapeHtml( $title ) ?></h1>
<?php $form->setAttribute( 'action', $this->url( 'test', array( 'action' => 'add' ) ) );
$form->prepare();

//echo $this->form()->openTag( $form );
//echo $this->formHidden( $form->get( 'id' ) );
//echo $this->formRow( $form->get( 'email' ) );
//echo $this->formRow( $form->get( 'comment' ) );
//echo $this->formSubmit( $form->get( 'submit' ) );
//echo $this->form()->closeTag();

//instead of per-line implementation we can use the entire form function display:
echo $this->form()->openTag( $form );
echo $this->formCollection($form);
echo $this->form()->closeTag();
