<?php
extract( $pagination );
$pages = ceil( $total/$posts_per_page );
echo '<ul class="pagination">';
if ( $current > 1 ) {
    echo '<li><a href="/search/page/' . ( $current -1 ) . '">' . $this->translate( 'Previous' ) . '</a></li>';
}
for( $i = 1; $i <= $pages; $i++ ) {
    echo '<li>';
    if ( $current == $i ) {
        echo '<span class="current">' . $i . '</span>';
    } else {
        echo '<a href="/search/page/' . $i . '?search=' . $query . '">' . $i . '</a>';
    }
    echo '</li>';
}
if ( $current < ( $total - 1 ) ) {
    echo '<li><a href="/search/page/' . ( $current + 1 ) . '?search=' . $query . '">' . $this->translate( 'Next' ) . '</a></li>';
}
echo '</ul>';