<?php
if ( $response ) {
    if ( $response->hits->total > 0 ) {
        echo '<h2>' . $response->hits->total .
            $translate->translatePlural( ' result found for ', ' results found for ', $response->hits->total ) . $query .
            '</h2>';
        echo '<ul class="searchResults">';
        foreach( $response->hits->hits as $hit ) {
            echo '<li>' . $hit->_source->comment . '</li>';
        }
        echo '</ul>';
    } else {
        echo $translate->translate( 'Nothing found for ' ) . $query;
    }
    if ( $pagination ) {
        extract( $pagination );
        $pages = ceil( $total/$posts_per_page );
        echo '<ul class="pagination">';
        if ( $current > 1 ) {
            echo '<li><a href="/search/search/page/' . ( $current + 1 ) . '">' . $translate->translate( 'Previous' ) . '</a></li>';
        }
        for( $i = 1; $i <= $pages; $i++ ) {
            echo '<li>';
            if ( $current == $i ) {
                echo '<span class="current">' . $i . '</span>';
            } else {
                echo '<a href="/search/search/page/' . $i . '">' . $i . '</a>';
            }
            echo '</li>';
        }
        if ( $current < ( $total - 1 ) ) {
            echo '<li><a href="/search/search/page/' . ( $current + 1 ) . '?' . $query . '">' . $translate->translate( 'Next' ) . '</a></li>';
        }
        echo '</ul>';
    }
}