<?php
if ( $response ) {
    if ( !empty( $response->error ) ) {
        echo '<p class="error">' . $response->error . '</p>';
        echo '<p class="error">' . $this->translate( 'If this error repeats, please, contact administrator' ) . '</p>';
    } else if ( $response->hits->total > 0 ) {
        echo '<h2>' . $response->hits->total .
            $this->translatePlural( ' result found for ', ' results found for ', $response->hits->total ) . $query .
            '</h2>';
        echo '<ul class="searchResults">';
        foreach( $response->hits->hits as $hit ) {
            echo '<li>' . $hit->_source->comment . '</li>';
        }
        echo '</ul>';
    } else {
        echo $this->translate( 'Nothing found for ' ) . $query;
    }
    if ( $pagination ) {
        include( 'pagination.phtml' );
    }
}